name = "juvix-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Juvix", "Tests"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Juvix"

[[lean_lib]]
name = "Tests"
